### ISSUE TITLE
When will the code be available?

### ISSUE THREAD

**Issue by kaixinbear** [qcraftai/simtrack#1]

**Comment by xiaodongyang** [comment]
Hopefully will be available before the ICCV conference.

**Comment by FutureRainbow** [comment]
Excited for this!

**Comment by ryontang** [comment]
感谢分享，保持关注！

**Comment by pratikai** [comment]
Excited for this!

**Comment by dingfuzhou** [comment]
Impressive work and hoping for the code!

**Comment by dingfuzhou** [comment]
Impressive work and hoping for the code!

**Comment by Shaoqing26** [comment]
> Hopefully will be available before the ICCV conference.

Hi, is there has any plan for releasing the code?

**Comment by JayChan-USTC** [comment]
1

**Comment by xiaodongyang** [comment]
We've released the code and model. Please check them out.

**Comment by turboxin** [comment]
Hi @xiaodongyang， thanks for opensourcing this great work. It seems that only detection part code is released for now, is that right? Any plan to release the whole code including tracking part?

Thanks a lot!

**Comment by xiaodongyang** [comment]
@turboxin Thanks for the feedback. It's updated.
