### ISSUE TITLE
It seems that point_pillars_tracking.py is needed

### ISSUE THREAD

**Issue by lucksonzhen** [qcraftai/simtrack#15]
when i train the model using command line in the tutorial, I got this :
`Traceback (most recent call last):
  File "./tools/train.py", line 13, in <module>
    from det3d.models import build_detector
  File "/home/lz/task3/simtrack/simtrack/det3d/models/__init__.py", line 13, in <module>
    from .detectors import *  # noqa: F401,F403
  File "/home/lz/task3/simtrack/simtrack/det3d/models/detectors/__init__.py", line 3, in <module>
    from .point_pillars_tracking import PointPillarsTracking
ModuleNotFoundError: No module named 'det3d.models.detectors.point_pillars_tracking'`
The error occurs because there is no point_pillars_tracking.py in /home/lz/task3/simtrack/simtrack/det3d/models/detectors, but a voxelnet.py which has been commented out.
Can anybodyhelp me ?

**Comment by zzm-hl** [comment]
I have the same problem.

**Comment by hoqolo** [comment]
How to solve this problem? Looking forward to your reply
