### ISSUE TITLE
About motion compensation

### ISSUE THREAD

**Issue by xibinyue** [qcraftai/simtrack#18]
Thanks your fantastic work first, and I have a problem while view the code, did you do anything about motion compensation? I saw you use the matrix between two sweep lidar points to concat the points, but I did not see motion process when concat two sweeps lidar points, maybe I missed. If do not do MC, is there the problem for the objects with big velocity?

Look forward to your kind reply，Thank you

**Comment by xiaodongyang** [comment]
See https://github.com/qcraftai/simtrack/blob/main/det3d/datasets/pipelines/preprocess.py#L154

**Comment by bbappyuanyuan** [comment]
Thanks for your great work first! I read through AssignTracking(). From my understanding, the target / model output is composed of tracked_objects at t-1 and new_objects at t. To get results at t, it seems the tracked_objects need motion compensation from t-1 to t. But I didn't see this process in inference. What am I doing wrong?
