### ISSUE TITLE
Request Simtrack on WOD

### ISSUE THREAD

**Issue by huixiancheng** [qcraftai/simtrack#31]
Will consider releasing this part of the code？ Thx a lot.

**Comment by sean-wade** [comment]
> Will consider releasing this part of the code？ Thx a lot.

I have done some work on it: https://github.com/sean-wade/simtrack_waymo
You can reference it.

**Comment by huixiancheng** [comment]
Greak Work！:thumbsup::thumbsup: Thanks a lot for your work and open source sharing. :bow: :bow:

**Comment by huixiancheng** [comment]
I am a green hand in the field of tracking. Would you be willing to share your email or WeChat for future consultation and discussion? :bow: @sean-wade

**Comment by sean-wade** [comment]
> I am a green hand in the field of tracking. Would you be willing to share your email or WeChat for future consultation and discussion? 🙇 @sean-wade

You can leave messages under my project. I will reply you asap.

**Comment by huixiancheng** [comment]
thx for your kind reply.
