### ISSUE TITLE
ModuleNotFoundError: No module named 'det3d.models.detectors.point_pillars_tracking'

### ISSUE THREAD

**Issue by hxm91** [qcraftai/simtrack#32]
Hi, thank u very much for this great work.
 I had a problem when I was trying out the Codes. Then I found out that this file '/det3d/models/detectors/point_pillars_tracking.py'  is missing.
<img width="614" alt="image" src="https://github.com/qcraftai/simtrack/assets/50672789/c8684b8a-0ce8-4046-b234-c09446034e71">

So my question is, forgot to upload this file?  Looking forward to your reply.

**Comment by chenxuluo** [comment]
Sorry for the confusion.  point_pillars_tracking.py is not used. We updated the init file.

**Comment by hxm91** [comment]
Thank you so much for your reply.
