### ISSUE TITLE
Unable to download pretrained model

### ISSUE THREAD

**Issue by richard-robotics** [qcraftai/simtrack#33]
Hi, I'm trying to download the pretrained model using the link in INSTALL.md. That link seem to point to a Azure storage service. I tried many accounts and all got error 

`AADSTS50177: User account '***' from identity provider 'live.com' does not exist in tenant 'Massachusetts Institute of Technology' and cannot access the application '00000003-0000-0ff1-ce00-000000000000'(Office 365 SharePoint Online) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.`

Have you made this file public?

**Comment by chenxuluo** [comment]
Try this link: https://drive.google.com/file/d/19vHeJflaPcX4xTn2vbjwWO46EdWeNkB8/view?usp=drive_link

**Comment by richard-robotics** [comment]
That worked. Thank you!

**Comment by shoushou0315** [comment]
> [https://drive.google.com/file/d/19vHeJflaPcX4xTn2vbjwWO46EdWeNkB8](https://drive.google.com/file/d/19vHeJflaPcX4xTn2vbjwWO46EdWeNkB8/view?usp=drive_link)

file not foundT_T

**Comment by wxk1316** [comment]
> That worked. Thank you!

Hello, sorry to bother you. The link is broken.


> Try this link: https://drive.google.com/file/d/19vHeJflaPcX4xTn2vbjwWO46EdWeNkB8/view?usp=drive_link

**Comment by wxk1316** [comment]
> That worked. Thank you!
Hello, sorry to bother you. Could you please share the pre-trained model? This link is no longer valid, and it's very important to me. Thank you so much.

**Comment by wxk1316** [comment]
> Try this link: https://drive.google.com/file/d/19vHeJflaPcX4xTn2vbjwWO46EdWeNkB8/view?usp=drive_link

Hello, sorry to bother you. Could you please share the pre-trained model? This link is no longer valid, and it's very important to me. Thank you so much.

**Comment by wxk1316** [comment]
> > [https://drive.google.com/file/d/19vHeJflaPcX4xTn2vbjwWO46EdWeNkB8](https://drive.google.com/file/d/19vHeJflaPcX4xTn2vbjwWO46EdWeNkB8/view?usp=drive_link)
> 
> file not foundT_T

Hello, sorry to bother you. Could you please share the pre-trained model? This link is no longer valid, and it's very important to me. Thank you so much.
