### ISSUE TITLE
The difference with centerpoint.

### ISSUE THREAD

**Issue by dwy927** [qcraftai/simtrack#4]
I have one question, does the model structure of the simTrack is completely the same as CenterPoint? 
And the only difference is the post-processing. Am I right? Do I miss something important?

**Comment by xiaodongyang** [comment]
SimTrack adopts the center-based representation, but it is fundamentally different from CenterPoint. Please double check our paper and implementation.

**Comment by dwy927** [comment]
I just read the code, the only difference I found lies in post-processing in inference and label assigned in training. 

Could you please specify the other important difference by code link? Thanks a lot.
