### ISSUE TITLE
where is the code of the “Motion Updating Branch” module proposed in the paper？

### ISSUE THREAD

**Issue by JayChan-USTC** [qcraftai/simtrack#5]
Hello, where is the code of the “Motion Updating Branch” module proposed in the paper？
I didn't find it, Could you tell me？

**Comment by dwy927** [comment]
Me too. The released code seems not use the predicted velocity to update the boxes location from previous frame to current frame.

**Comment by JayChan-USTC** [comment]
the predicted velocity is used in the CenterPoint for tracking

**Comment by dwy927** [comment]
Yes, but in simTrack it seems not use this information.

**Comment by AlmoonYsl** [comment]
Me too, I can't find the code of the "Motion Updating".

**Comment by chenxuluo** [comment]
see https://github.com/qcraftai/simtrack/blob/main/det3d/datasets/pipelines/preprocess.py#L154
